### ISSUE TITLE
Erro quando não tem Cartão de Crédito

### ISSUE THREAD

**Issue by GuidoBR** [henriquebastos/itauscraper#2]
Ao rodar o itauscrapper numa conta sem cartão de crédito, recebo essa mensagem de erro:
```
Traceback (most recent call last):
  File "/home/guido/.pyenv/versions/tools3/bin/itauscraper", line 11, in <module>
    load_entry_point('itauscraper==1.0', 'console_scripts', 'itauscraper')()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/cli.py", line 48, in main
    summary, data = itau.cartao()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/scraper.py", line 78, in cartao
    url = page.url_menu_current()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/pages.py", line 99, in url_menu_current
    return self._url_menu('atuais')
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/pages.py", line 93, in _url_menu
    href = nl[-1]
IndexError: list index out of range
```

**Comment by gabrielpaivadev** [comment]
Mesmo erro aqui.

**Comment by lucasrcezimbra** [comment]
Por algum motivo, quando a conta não tem cartão de crédito associado, no menu não aparece a opção Saldo / Extrato.
![Menus COM/SEM Saldo Itaú](https://user-images.githubusercontent.com/7042915/32252147-39e9736e-be7b-11e7-9d9e-9761043108f6.png)

E a URL [usada](https://github.com/henriquebastos/itauscraper/blob/master/itauscraper/scraper.py#L53) no itauscraper (https://ww70.itau.com.br/M/SaldoExtratoLancamentos.aspx) redireciona para esse erro: 
![error-itauscraper](https://user-images.githubusercontent.com/7042915/32251675-30d6d804-be79-11e7-93d0-db4621768075.png)

Porém, nesse caso, temos uma URL (https://ww70.itau.com.br/M/relacaocomprovantes.aspx) com os comprovantes dos últimos 90 dias onde podemos pegar os dados.

Eu vou tentar abrir um PR corrigindo isso.

**Comment by lucasrcezimbra** [comment]
Testei aqui e a URL dos comprovantes (https://ww70.itau.com.br/M/relacaocomprovantes.aspx) que eu havia citado mostra somente transferências e depósitos, não mostra os itens do cartão de débito, então creio que não sirva para o scraper :cry::cry:

Outra opção é tentar usar a API do app mobile para pegar o extrato. Vou testar a viabilidade disso.

**Comment by gabrielpaivadev** [comment]
Qualquer novidade sobre a API, joga aqui @Lrcezimbra

**Comment by ludufre** [comment]
@Lrcezimbra conseguiu evoluir nisso? Estou apanhando com o Wireshark sem sucesso...

**Comment by lucasrcezimbra** [comment]
@ludufre ainda não tive tempo de ver isso, se conseguir evoluir eu comento aqui.
Nunca usei o Wireshark, normalmente uso o [Chales](https://www.charlesproxy.com/) ou o [Fiddler](https://www.telerik.com/fiddler), talvez te ajudem.

**Comment by henriquebastos** [comment]
Isso não funciona mais. Tô começando a rascunhar uma alternativa em #8.
