### ISSUE TITLE
Linha de saldo de aplicação automática está aparecendo

### ISSUE THREAD

**Issue by rvogel** [henriquebastos/itauscraper#5]
Já resolvi, adicionando uma linha (a última) na "def is_balance(s):" do "converter.py":

    return s in ('S A L D O',
                 '(-) SALDO A LIBERAR',
                 'SALDO FINAL DISPONIVEL',
                 'SALDO ANTERIOR',
                 'SDO CTA/APL AUTOMATICAS')

**Comment by henriquebastos** [comment]
Legal. Pode mandar um Pull Request? ;-)
