### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ccrvlh** [henriquebastos/itauscraper#6]
To recebendo esse erro em duas linhas:

```
File "/Users/User/Documents/Envs/itauscraper/itauscraper/scraper.py", line 60, in extrato
    url = page.url_max_period()
  File "/Users/User/Documents/Envs/itauscraper/itauscraper/pages.py", line 73, in url_max_period
    href = nl[-1]
```

Alguém já viu este erro?
Algo que possa estar fazendo errado do meu lado, ou que precise de algum ajuste no código?

Obrigado!

_PS: Será esta a mesma lógica utilizada pelo GuiaBolso para pegar extratos?_

**Comment by ccrvlh** [comment]
Acabei de perceber que com os links usados pelo script o Itaú não mostra o Extrato nem a fatura do cartão de crédito, não sei exatamente por que - será que tem alguma solução para contornar?

**Comment by huogerac** [comment]
Acredito que o itau desabilitou o login via api mobile: 
`https://ww70.itau.com.br/M/`

**Comment by ludufre** [comment]
O login até que funciona, o problema é que a parte de extrato da conta corrente não aparece...

**Comment by marcosvpj** [comment]
Teste aqui e recebi o mesmo erro.
Para investigar segui os passos navegando manualmente pelo modo mobile e as opções de extrato, tanto para cartão quanto para conta corrente não aparecem mais.

Acabaram com a nossa diversão?

**Comment by rodgasp** [comment]
Algum progresso neste erro pessoal?

**Comment by marcosvpj** [comment]
@rodgasp, pelo que eu analisei do erro, o problema é que o Itaú não disponibiliza mais essa funcionalidade na versão mobile do site. Assim não tem mais de onde tirar essas informações.

Eu dei uma navegada pelo mobile e infelizmente não achei nenhum outro ponto em que possamos extrair esses dados.

Se alguém tiver alguma outra idéia de onde podemos tirar esses dados podemos atualizar o projeto, senão não vejo solução para o problema.

**Comment by henriquebastos** [comment]
Isso não funciona mais. Tô começando a rascunhar uma alternativa em #8.
