### ISSUE TITLE
Erro ItauScraper Java

### ISSUE THREAD

**Issue by krause-dj** [henriquebastos/itauscraper#7]
Estou fazendo uma versão do **Scraper** em **JAVA** e estou com o erro abaixo: 
![prtscr capture](https://user-images.githubusercontent.com/8337704/34846941-ed19b09e-f700-11e7-8a7f-2546244d843d.jpg)

Conforme o [código](https://github.com/oDjonathanKrause/JavaItauScraper/blob/master/src/main/java/drk/itauscrapper/Login.java), estou fazendo o GET para pegar uma sessão e fazendo o POST com os parâmetros e headers necessários (os mesmos do feito em Python do @henriquebastos).

Acredito que está seja a página de redirecionamento default em caso de erro. Penso que o erro esteja no método doLogin() que faz o POST.

**Comment by henriquebastos** [comment]
Isso não funciona mais. Tô começando a rascunhar uma alternativa em #8.
